export const data = [{
    id: 1,
    titulo: "Batman: El caballero de la noche",
    genero: "Accion, Crimen",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2008,
    clasificacion: 9.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
    precio: 145,
    VecesAlquilada: 0
},
{
    id: 2,
    titulo: "Pecadores",
    genero: "Terror, Thriller",
    director: "Ryan Coogler",
    pais: "EEUU",
    anio: 2025,
    clasificacion: 7.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 3,
    titulo: "Mission: Impossible - The Final Reckoning ",
    genero: "Accion",
    director: "Christopher McQuarrie",
    pais: "EEUU",
    anio: 2025,
    clasificacion: 8.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 4,
    titulo: "Thor: Ragnarok ",
    genero: "Ciencia ficcion",
    director: "Taika Waititi",
    pais: "EEUU",
    anio: 2017,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    precio: 155,
    VecesAlquilada: 0
},
{
    id: 5,
    titulo: "Jurassic World: Fallen Kingdom",
    genero: "Ciencia ficcion, Accion, Aventura",
    director: "Michael Crichton",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 7.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/270MrJNqJovumHXGE6SSt0zwUIF.jpg",
    precio: 136,
    VecesAlquilada: 0
},
{
    id: 6,
    titulo: "Avengers: Infinity War",
    genero: "Aventura, Ciencia ficcion",
    director: "Joe Russo",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    precio: 248,
    VecesAlquilada: 0
},
{
    id: 7,
    titulo: "Deadpool 2",
    genero: "Accion, Comedia",
    director: "David Leitch",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 8.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
    precio: 215,
    VecesAlquilada: 0
},
{
    id: 8,
    titulo: "Kick-Ass",
    genero: "Accion, Comedia",
    director: "Matthew Vaughn",
    pais: "EEUU",
    anio: 2010,
    clasificacion: 7.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 9,
    titulo: "Inception",
    genero: "Ciencia ficcion, Accion",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2010,
    clasificacion: 8.8,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 10,
    titulo: "Interstellar",
    genero: "Ciencia ficcion, Drama",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2014,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    precio: 220,
    VecesAlquilada: 0
},
{
    id: 11,
    titulo: "The Matrix",
    genero: "Ciencia ficcion, Accion",
    director: "Lana Wachowski, Lilly Wachowski",
    pais: "EEUU",
    anio: 1999,
    clasificacion: 8.7,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 12,
    titulo: "Gladiator",
    genero: "Accion, Drama",
    director: "Ridley Scott",
    pais: "EEUU",
    anio: 2000,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    precio: 175,
    VecesAlquilada: 0
},
{
    id: 13,
    titulo: "The Godfather",
    genero: "Crimen, Drama",
    director: "Francis Ford Coppola",
    pais: "EEUU",
    anio: 1972,
    clasificacion: 9.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    precio: 250,
    VecesAlquilada: 0
},
{
    id: 14,
    titulo: "The Shawshank Redemption",
    genero: "Drama, Crimen",
    director: "Frank Darabont",
    pais: "EEUU",
    anio: 1994,
    clasificacion: 9.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    precio: 240,
    VecesAlquilada: 0
},
{
    id: 15,
    titulo: "Pulp Fiction",
    genero: "Crimen, Drama",
    director: "Quentin Tarantino",
    pais: "EEUU",
    anio: 1994,
    clasificacion: 8.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/dM2w364MScsjFf8pfMbaWUcWrR.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 16,
    titulo: "Fight Club",
    genero: "Drama",
    director: "David Fincher",
    pais: "EEUU",
    anio: 1999,
    clasificacion: 8.8,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 17,
    titulo: "Forrest Gump",
    genero: "Drama, Romance",
    director: "Robert Zemeckis",
    pais: "EEUU",
    anio: 1994,
    clasificacion: 8.8,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    precio: 195,
    VecesAlquilada: 0
},
{
    id: 18,
    titulo: "The Dark Knight Rises",
    genero: "Accion, Thriller",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2012,
    clasificacion: 8.4,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/85cWkCVftiVs0BVey6pxX8uNmLt.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 19,
    titulo: "The Lord of the Rings: The Fellowship of the Ring",
    genero: "Aventura, Fantasia",
    director: "Peter Jackson",
    pais: "Nueva Zelanda",
    anio: 2001,
    clasificacion: 8.8,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    precio: 230,
    VecesAlquilada: 0
},
{
    id: 20,
    titulo: "The Lord of the Rings: The Two Towers",
    genero: "Aventura, Fantasia",
    director: "Peter Jackson",
    pais: "Nueva Zelanda",
    anio: 2002,
    clasificacion: 8.7,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    precio: 230,
    VecesAlquilada: 0
},
{
    id: 21,
    titulo: "The Lord of the Rings: The Return of the King",
    genero: "Aventura, Fantasia",
    director: "Peter Jackson",
    pais: "Nueva Zelanda",
    anio: 2003,
    clasificacion: 8.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    precio: 240,
    VecesAlquilada: 0
},
{
    id: 22,
    titulo: "Star Wars: Episode IV - A New Hope",
    genero: "Ciencia ficcion, Aventura",
    director: "George Lucas",
    pais: "EEUU",
    anio: 1977,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 23,
    titulo: "Star Wars: Episode V - The Empire Strikes Back",
    genero: "Ciencia ficcion, Aventura",
    director: "Irvin Kershner",
    pais: "EEUU",
    anio: 1980,
    clasificacion: 8.7,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
    precio: 215,
    VecesAlquilada: 0
},
{
    id: 24,
    titulo: "Star Wars: Episode VI - Return of the Jedi",
    genero: "Ciencia ficcion, Aventura",
    director: "Richard Marquand",
    pais: "EEUU",
    anio: 1983,
    clasificacion: 8.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mDCBQNhR6R0PVFucJl0O4Hp5klZ.jpg",
    precio: 215,
    VecesAlquilada: 0
},
{
    id: 25,
    titulo: "Avatar",
    genero: "Ciencia ficcion, Aventura",
    director: "James Cameron",
    pais: "EEUU",
    anio: 2009,
    clasificacion: 7.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    precio: 220,
    VecesAlquilada: 0
},
{
    id: 26,
    titulo: "Titanic",
    genero: "Drama, Romance",
    director: "James Cameron",
    pais: "EEUU",
    anio: 1997,
    clasificacion: 7.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 27,
    titulo: "Jurassic Park",
    genero: "Ciencia ficcion, Aventura",
    director: "Steven Spielberg",
    pais: "EEUU",
    anio: 1993,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/c414cDeQ9b6qLPLeKmiJuLDUREJ.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 28,
    titulo: "The Lion King",
    genero: "Animacion, Aventura",
    director: "Roger Allers, Rob Minkoff",
    pais: "EEUU",
    anio: 1994,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 29,
    titulo: "Toy Story",
    genero: "Animacion, Aventura",
    director: "John Lasseter",
    pais: "EEUU",
    anio: 1995,
    clasificacion: 8.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 30,
    titulo: "Finding Nemo",
    genero: "Animacion, Aventura",
    director: "Andrew Stanton",
    pais: "EEUU",
    anio: 2003,
    clasificacion: 8.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
    precio: 175,
    VecesAlquilada: 0
},
{
    id: 31,
    titulo: "Shrek",
    genero: "Animacion, Comedia",
    director: "Andrew Adamson, Vicky Jenson",
    pais: "EEUU",
    anio: 2001,
    clasificacion: 7.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
    precio: 170,
    VecesAlquilada: 0
},
{
    id: 32,
    titulo: "Spider-Man: No Way Home",
    genero: "Accion, Ciencia ficcion",
    director: "Jon Watts",
    pais: "EEUU",
    anio: 2021,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    precio: 240,
    VecesAlquilada: 0
},
{
    id: 33,
    titulo: "Black Panther",
    genero: "Accion, Aventura",
    director: "Ryan Coogler",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 7.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 34,
    titulo: "Doctor Strange",
    genero: "Accion, Fantasia",
    director: "Scott Derrickson",
    pais: "EEUU",
    anio: 2016,
    clasificacion: 7.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 35,
    titulo: "Guardians of the Galaxy",
    genero: "Accion, Ciencia ficcion",
    director: "James Gunn",
    pais: "EEUU",
    anio: 2014,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 36,
    titulo: "Iron Man",
    genero: "Accion, Ciencia ficcion",
    director: "Jon Favreau",
    pais: "EEUU",
    anio: 2008,
    clasificacion: 7.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 37,
    titulo: "Captain America: The Winter Soldier",
    genero: "Accion, Ciencia ficcion",
    director: "Anthony Russo, Joe Russo",
    pais: "EEUU",
    anio: 2014,
    clasificacion: 7.7,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
    precio: 205,
    VecesAlquilada: 0
},
{
    id: 38,
    titulo: "Ant-Man",
    genero: "Accion, Ciencia ficcion",
    director: "Peyton Reed",
    pais: "EEUU",
    anio: 2015,
    clasificacion: 7.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/D6e8RJf2qUstnfkTslTXNTUAlT.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 39,
    titulo: "Wonder Woman",
    genero: "Accion, Fantasia",
    director: "Patty Jenkins",
    pais: "EEUU",
    anio: 2017,
    clasificacion: 7.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/imekS7f1OuHyUP2LAiTEM0zBzUz.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 40,
    titulo: "Aquaman",
    genero: "Accion, Fantasia",
    director: "James Wan",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 6.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/xLPffWMhMj1l50ND3KchMjYoKmE.jpg",
    precio: 195,
    VecesAlquilada: 0
},
{
    id: 41,
    titulo: "Joker",
    genero: "Crimen, Drama",
    director: "Todd Phillips",
    pais: "EEUU",
    anio: 2019,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    precio: 220,
    VecesAlquilada: 0
},
{
    id: 42,
    titulo: "The Prestige",
    genero: "Drama, Misterio",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2006,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 43,
    titulo: "The Departed",
    genero: "Crimen, Thriller",
    director: "Martin Scorsese",
    pais: "EEUU",
    anio: 2006,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jyAgiqVSx5fl0NNj7WoGGKweXrL.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 44,
    titulo: "The Wolf of Wall Street",
    genero: "Crimen, Comedia",
    director: "Martin Scorsese",
    pais: "EEUU",
    anio: 2013,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 45,
    titulo: "Django Unchained",
    genero: "Drama, Western",
    director: "Quentin Tarantino",
    pais: "EEUU",
    anio: 2012,
    clasificacion: 8.4,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 46,
    titulo: "Inglourious Basterds",
    genero: "Accion, Guerra",
    director: "Quentin Tarantino",
    pais: "EEUU",
    anio: 2009,
    clasificacion: 8.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ai0LXkzVM3hMJYxWwK0w7uwIGd9.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 47,
    titulo: "Mad Max: Fury Road",
    genero: "Accion, Aventura",
    director: "George Miller",
    pais: "Australia",
    anio: 2015,
    clasificacion: 8.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 48,
    titulo: "The Revenant",
    genero: "Aventura, Drama",
    director: "Alejandro G. Iñárritu",
    pais: "EEUU",
    anio: 2015,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oXUWEc5i3wYyFnL1Ycu8ppxxPvs.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 49,
    titulo: "La La Land",
    genero: "Comedia, Drama, Romance",
    director: "Damien Chazelle",
    pais: "EEUU",
    anio: 2016,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 50,
    titulo: "Whiplash",
    genero: "Drama, Musica",
    director: "Damien Chazelle",
    pais: "EEUU",
    anio: 2014,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oPxnRhyAIzJKGUEdSiwTJQBa6hz.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 51,
    titulo: "Parasite",
    genero: "Drama, Thriller",
    director: "Bong Joon-ho",
    pais: "Corea del Sur",
    anio: 2019,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 52,
    titulo: "Oldboy",
    genero: "Accion, Thriller",
    director: "Park Chan-wook",
    pais: "Corea del Sur",
    anio: 2003,
    clasificacion: 8.4,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pWDtjs568ZfOTMbURQBYuT4QxkC.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 53,
    titulo: "Spirited Away",
    genero: "Animacion, Fantasia",
    director: "Hayao Miyazaki",
    pais: "Japon",
    anio: 2001,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 54,
    titulo: "Your Name",
    genero: "Animacion, Romance",
    director: "Makoto Shinkai",
    pais: "Japon",
    anio: 2016,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/q719jXXEzOoYaps6babgKnONONX.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 55,
    titulo: "The Intouchables",
    genero: "Comedia, Drama",
    director: "Olivier Nakache, Éric Toledano",
    pais: "Francia",
    anio: 2011,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/w6XG1rN6vGq5nA6l6h2oE2leuuk.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 56,
    titulo: "Amélie",
    genero: "Comedia, Romance",
    director: "Jean-Pierre Jeunet",
    pais: "Francia",
    anio: 2001,
    clasificacion: 8.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sZb1g6QGyoGq2x1r3Qz5bY1l6iF.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 57,
    titulo: "Pan's Labyrinth",
    genero: "Fantasia, Drama",
    director: "Guillermo del Toro",
    pais: "España",
    anio: 2006,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6n9DK7brOb3Ec2Q0LMAf3xAEQvC.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 58,
    titulo: "Life Is Beautiful",
    genero: "Comedia, Drama",
    director: "Roberto Benigni",
    pais: "Italia",
    anio: 1997,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f7DImXDebOs148U4uPjI61iDvaK.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 59,
    titulo: "City of God",
    genero: "Crimen, Drama",
    director: "Fernando Meirelles, Kátia Lund",
    pais: "Brasil",
    anio: 2002,
    clasificacion: 8.4,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4RS3yUGJ6yGzK1A4Lg6W4WkV9nG.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 60,
    titulo: "The Pianist",
    genero: "Drama, Guerra",
    director: "Roman Polanski",
    pais: "Francia",
    anio: 2002,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 61,
    titulo: "Schindler's List",
    genero: "Drama, Historia",
    director: "Steven Spielberg",
    pais: "EEUU",
    anio: 1993,
    clasificacion: 8.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/c8Ass7acuOe4za6DhSattE359gr.jpg",
    precio: 220,
    VecesAlquilada: 0
},
{
    id: 62,
    titulo: "The Green Mile",
    genero: "Drama, Fantasia",
    director: "Frank Darabont",
    pais: "EEUU",
    anio: 1999,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sOHqdY1RnSn6kcfAHKu28jvTebE.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 63,
    titulo: "Se7en",
    genero: "Crimen, Thriller",
    director: "David Fincher",
    pais: "EEUU",
    anio: 1995,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 64,
    titulo: "The Silence of the Lambs",
    genero: "Crimen, Thriller",
    director: "Jonathan Demme",
    pais: "EEUU",
    anio: 1991,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 65,
    titulo: "The Usual Suspects",
    genero: "Crimen, Misterio",
    director: "Bryan Singer",
    pais: "EEUU",
    anio: 1995,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 66,
    titulo: "American Beauty",
    genero: "Drama",
    director: "Sam Mendes",
    pais: "EEUU",
    anio: 1999,
    clasificacion: 8.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/wby9315QzVKdW9BonAefg8jGTTb.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 67,
    titulo: "The Truman Show",
    genero: "Comedia, Drama",
    director: "Peter Weir",
    pais: "EEUU",
    anio: 1998,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 68,
    titulo: "The Grand Budapest Hotel",
    genero: "Comedia, Crimen",
    director: "Wes Anderson",
    pais: "EEUU",
    anio: 2014,
    clasificacion: 8.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/nX5XotM9yprCKarRH4fzOq1VM1J.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 69,
    titulo: "The Social Network",
    genero: "Drama",
    director: "David Fincher",
    pais: "EEUU",
    anio: 2010,
    clasificacion: 7.7,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 70,
    titulo: "The Imitation Game",
    genero: "Drama, Guerra",
    director: "Morten Tyldum",
    pais: "Reino Unido",
    anio: 2014,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 71,
    titulo: "A Beautiful Mind",
    genero: "Drama, Romance",
    director: "Ron Howard",
    pais: "EEUU",
    anio: 2001,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 72,
    titulo: "Slumdog Millionaire",
    genero: "Drama, Romance",
    director: "Danny Boyle",
    pais: "Reino Unido",
    anio: 2008,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iNDVb1C1l8WvK4R1g1JrR6ZQ7tG.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 73,
    titulo: "The Sixth Sense",
    genero: "Drama, Misterio",
    director: "M. Night Shyamalan",
    pais: "EEUU",
    anio: 1999,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 74,
    titulo: "Memento",
    genero: "Misterio, Thriller",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2000,
    clasificacion: 8.4,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fQMSaP88cf1nz4qwuNEEFtazuDM.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 75,
    titulo: "The Big Lebowski",
    genero: "Comedia, Crimen",
    director: "Joel Coen, Ethan Coen",
    pais: "EEUU",
    anio: 1998,
    clasificacion: 8.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5gTQkKgfHNW5vCqfAKk5n6hVbqQ.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 76,
    titulo: "No Country for Old Men",
    genero: "Crimen, Thriller",
    director: "Joel Coen, Ethan Coen",
    pais: "EEUU",
    anio: 2007,
    clasificacion: 8.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6d5XOczc226jECq0LIX0siKtgHR.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 77,
    titulo: "Blade Runner 2049",
    genero: "Ciencia ficcion, Thriller",
    director: "Denis Villeneuve",
    pais: "EEUU",
    anio: 2017,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 78,
    titulo: "Arrival",
    genero: "Ciencia ficcion, Drama",
    director: "Denis Villeneuve",
    pais: "EEUU",
    anio: 2016,
    clasificacion: 7.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    precio: 190,
    VecesAlquilada: 0
}
]