export const data = [{
    id: 12345,
    titulo: "Batman: El caballero de la noche",
    genero: "Accion, Crimen",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2008,
    clasificacion: 9.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
    precio: 145,
    VecesAlquilada: 0
},
{
    id: 23456,
    titulo: "Pecadores",
    genero: "Terror, Thriller",
    director: "Ryan Coogler",
    pais: "EEUU",
    anio: 2025,
    clasificacion: 7.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 34567,
    titulo: "Mission: Impossible - The Final Reckoning ",
    genero: "Accion",
    director: "Christopher McQuarrie",
    pais: "EEUU",
    anio: 2025,
    clasificacion: 8.1,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 45678,
    titulo: "Thor: Ragnarok ",
    genero: "Ciencia ficcion",
    director: "Taika Waititi",
    pais: "EEUU",
    anio: 2017,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    precio: 155,
    VecesAlquilada: 0
},
{
    id: 56789,
    titulo: "Jurassic World: Fallen Kingdom",
    genero: "Ciencia ficcion, Accion, Aventura",
    director: "Michael Crichton",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 7.3,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/270MrJNqJovumHXGE6SSt0zwUIF.jpg",
    precio: 136,
    VecesAlquilada: 0
},
{
    id: 67890,
    titulo: "Avengers: Infinity War",
    genero: "Aventura, Ciencia ficcion",
    director: "Joe Russo",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    precio: 248,
    VecesAlquilada: 0
},
{
    id: 78901,
    titulo: "Deadpool 2",
    genero: "Accion, Comedia",
    director: "David Leitch",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 8.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
    precio: 215,
    VecesAlquilada: 0
},
{
    id: 89012,
    titulo: "Kick-Ass",
    genero: "Accion, Comedia",
    director: "Matthew Vaughn",
    pais: "EEUU",
    anio: 2010,
    clasificacion: 7.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 90123,
    titulo: "Inception",
    genero: "Ciencia ficcion, Accion",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2010,
    clasificacion: 8.8,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 11223,
    titulo: "Interstellar",
    genero: "Ciencia ficcion, Drama",
    director: "Christopher Nolan",
    pais: "EEUU",
    anio: 2014,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    precio: 220,
    VecesAlquilada: 0
},
{
    id: 22334,
    titulo: "Matrix",
    genero: "Ciencia ficcion, Accion",
    director: "Lana Wachowski",
    pais: "EEUU",
    anio: 1999,
    clasificacion: 8.7,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 33445,
    titulo: "Gladiator",
    genero: "Accion, Drama",
    director: "Ridley Scott",
    pais: "EEUU",
    anio: 2000,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    precio: 175,
    VecesAlquilada: 0
},

{
    id: 44556,
    titulo: "El Padrino",
    genero: "Crimen, Drama",
    director: "Francis Ford Coppola",
    pais: "EEUU",
    anio: 1972,
    clasificacion: 9.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 66778,
    titulo: "Forrest Gump",
    genero: "Drama, Romance",
    director: "Robert Zemeckis",
    pais: "EEUU",
    anio: 1994,
    clasificacion: 8.8,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    precio: 170,
    VecesAlquilada: 0
},
{
    id: 77889,
    titulo: "El Señor de los Anillos: El Retorno del Rey",
    genero: "Aventura, Fantasia",
    director: "Peter Jackson",
    pais: "Nueva Zelanda",
    anio: 2003,
    clasificacion: 9.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    precio: 210,
    VecesAlquilada: 0
},
{
    id: 88990,
    titulo: "Titanic",
    genero: "Drama, Romance",
    director: "James Cameron",
    pais: "EEUU",
    anio: 1997,
    clasificacion: 8.2,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    precio: 180,
    VecesAlquilada: 0
},

{
    id: 10112,
    titulo: "La La Land",
    genero: "Comedia, Drama, Romance",
    director: "Damien Chazelle",
    pais: "EEUU",
    anio: 2016,
    clasificacion: 8.0,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    precio: 170,
    VecesAlquilada: 0
},


{
    id: 46802,
    titulo: "El Viaje de Chihiro",
    genero: "Animacion, Fantasia",
    director: "Hayao Miyazaki",
    pais: "Japon",
    anio: 2001,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 59123,
    titulo: "El Rey León",
    genero: "Animacion, Aventura",
    director: "Roger Allers",
    pais: "EEUU",
    anio: 1994,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    precio: 170,
    VecesAlquilada: 0
},

{
    id: 68234,
    titulo: "Coco",
    genero: "Animacion, Familia",
    director: "Lee Unkrich",
    pais: "EEUU",
    anio: 2017,
    clasificacion: 8.4,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    precio: 160,
    VecesAlquilada: 0
},
{
    id: 79345,
    titulo: "Parásitos",
    genero: "Drama, Thriller",
    director: "Bong Joon-ho",
    pais: "Corea del Sur",
    anio: 2019,
    clasificacion: 8.6,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    precio: 180,
    VecesAlquilada: 0
},
{
    id: 80456,
    titulo: "El Irlandés",
    genero: "Crimen, Drama",
    director: "Martin Scorsese",
    pais: "EEUU",
    anio: 2019,
    clasificacion: 7.9,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg",
    precio: 190,
    VecesAlquilada: 0
},
{
    id: 91567,
    titulo: "Joker",
    genero: "Crimen, Drama, Thriller",
    director: "Todd Phillips",
    pais: "EEUU",
    anio: 2019,
    clasificacion: 8.5,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    precio: 200,
    VecesAlquilada: 0
},
{
    id: 12678,
    titulo: "Spider-Man: Un nuevo universo",
    genero: "Animacion, Accion",
    director: "Bob Persichetti",
    pais: "EEUU",
    anio: 2018,
    clasificacion: 8.4,
    alquilada: false,
    imagen: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    precio: 170,
    VecesAlquilada: 0
}
]
